### ISSUE TITLE
The Pair option does not appear

### ISSUE THREAD

**Issue by 3khenrique** [aronsky/esphome-components#14]
Thank you for your incredible work. I am completely new to automation and just starting in this world. I recently purchased two LampSmart Pro lamps and would like to connect and automate them.

However, the service that should be exposed to pair with my lamps isn't available, and I can't send a pair command to connect them.

There's only one entity on my HA: 
![image](https://github.com/aronsky/esphome-components/assets/97890704/5dff623e-ad77-4764-8567-951dd5e0845f)

And I Have no options to make the pair working:
![image](https://github.com/aronsky/esphome-components/assets/97890704/86b45864-7c3e-499b-b16b-160031a854d0)

Here is my configuration:

```yaml
esphome:
  name: lampada

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Example configuration entry
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://aronsky/esphome-components

# LampSmart Pro
light:
  - platform: ble_adv_light
    type: lampsmart_pro
    name: lampada
    duration: 750
    default_transition_length: 0s
```
Any guidance on how to solve this issue would be greatly appreciated.
