### ISSUE TITLE
How to add multiple lights?

### ISSUE THREAD

**Issue by zolakt** [aronsky/esphome-components#29]
Sorry if this is a stupid question, but I can't figure it out. I see different examples.
I have 3 lights controlled by the Zhi Jia app. What is the proper way to configure that?

I tried adding 3 of everything (controller, light, button), and I can pair all the devices.
But whatever I change on any of them, it changes on all of them.

Here is my current config:
```
ble_adv_controller:
  - id: living_room_light_controller
    encoding: zhijia
  - id: kitchen_light_controller
    encoding: zhijia
  - id: bar_light_controller
    encoding: zhijia

light:
  - platform: ble_adv_controller
    ble_adv_controller_id: living_room_light_controller
    name: Living Room Light Controller
  - platform: ble_adv_controller
    ble_adv_controller_id: kitchen_light_controller
    name: Kitchen Light Controller
  - platform: ble_adv_controller
    ble_adv_controller_id: bar_light_controller
    name: Bar Light Controller

button:
  - platform: ble_adv_controller
    ble_adv_controller_id: living_room_light_controller
    name: Living Room Light Controller Pair
    cmd: pair
  - platform: ble_adv_controller
    ble_adv_controller_id: kitchen_light_controller
    name: Kitchen Light Controller Pair
    cmd: pair
  - platform: ble_adv_controller
    ble_adv_controller_id: bar_light_controller
    name: Bar Light Controller Pair
    cmd: pair
```

**Comment by aronsky** [comment]
When capturing data from the ZhiJia app, it shouldn't matter whether the actual light is powered or not, the app simply broadcasts the messages. So try to keep all the lights on, and toggle each of them via the app to verify that they toggle correctly - while sniffing the data coming through the app.

If that works, I think that setting the `forced_id` value that you see broadcast for each light, combined with the index, for each controller should fix the issue. So your controllers should look something like:

```yaml
ble_adv_controller:
  - id: living_room_light_controller
    encoding: zhijia
    variant: v2
    forced_id: 0xE8E075
    index: 1
  - id: kitchen_light_controller
    encoding: zhijia
    variant: v2
    forced_id: 0xE8E075
    index: 2
  - id: bar_light_controller
    encoding: zhijia
    variant: v2
    forced_id: 0xE8E075
    index: 3
```

If that doesn't work, try changing the `v2` to `v1`/`v0` for each light that doesn't function (for `v0`, change the `forced_id` to `0xE8E0`). And if it works but the lights toggled don't match your expectations, just play around with the indices.

**Comment by zolakt** [comment]
I'll try to sniff again, but that is pretty much what I have now. But still each controller affects all 3 lights.

```
ble_adv_controller:
  - id: living_room_light_controller
    encoding: zhijia
    forced_id: 0xE8E075
    index: 1
    show_config: true
  - id: bar_light_controller
    encoding: zhijia
    forced_id: 0xE8E075
    index: 2
    show_config: true
    reversed: true
  - id: kitchen_light_controller
    encoding: zhijia
    forced_id: 0xE8E075
    index: 3
    show_config: true
```

The issue is not if they work. All of them pair and work. But they aren't controlled separately. Every controller does the same thing, and affects all 3 light. I've even tried pairing/unpairing. It all seems to be the same thing. e.g. I pair the living room light with it's pair button, but then I unpair it by calling the kitchen unpair method.
