### ISSUE TITLE
How to pair lamp

### ISSUE THREAD

**Issue by Tinoyeet** [aronsky/esphome-components#36]
Sorry for bothering, but how do I pair with the lamp.
I've tried basically everything now from turning the lamp off and on to pressing on setup on the remote. My lamp uses the LampSmart Pro app on my phone and it works on there basically fine. I already tried to pair it with all of the encoding varients.

Here is my config if it helps:

```
external_components:
  # shorthand
  source: github://aronsky/esphome-components

esp32:
  board: esp32dev


ble_adv_controller:
  - id: my_controller
    encoding: lampsmart_pro

light:
  - platform: ble_adv_controller
    ble_adv_controller_id: my_controller
    name: LampSmart Light

button:
  - platform: ble_adv_controller
    ble_adv_controller_id: my_controller
    name: Pair
    # cmd: the action to be executed when the button is pressed
    # any of 'pair', 'unpair', 'custom', 'light_on', ...
    cmd: pair

```
Thanks for taking your time for reading.
