### ISSUE TITLE
unable to compile for tracking my remote

### ISSUE THREAD

**Issue by MichaelGrenier83** [aronsky/esphome-components#38]
Hi, here is my code

```
esphome:
  name: fan-contoller
  friendly_name: Fan contoller

external_components:
  - source:
      type: git
      url: https://github.com/aronsky/esphome-components

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan-Contoller Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

captive_portal:

web_server:

esp32_ble_tracker:
  scan_parameters:
    interval: 15ms
    window: 15ms
  on_ble_advertise:
    then:
      - lambda: 'ble_adv_static_handler->capture(x, true);'

ble_adv_controller:
  - id: my_controller
    encoding: fanlamp_pro
```
And here's my compile result

`|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/fan-contoller/src/esphome/components/ble_adv_controller/ble_adv_handler.cpp.o
Compiling .pioenvs/fan-contoller/src/esphome/components/captive_portal/captive_portal.cpp.o
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp: In member function 'void esphome::bleadvcontroller::HackESPBTDevice::get_raw_packet(esphome::bleadvcontroller::BleAdvParam&) const':
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp:283:26: error: 'const class esphome::bleadvcontroller::HackESPBTDevice' has no member named 'scan_result_'
  283 |     param.from_raw(this->scan_result_.ble_adv, this->scan_result_.adv_data_len);
      |                          ^~~~~~~~~~~~
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp:283:54: error: 'const class esphome::bleadvcontroller::HackESPBTDevice' has no member named 'scan_result_'
  283 |     param.from_raw(this->scan_result_.ble_adv, this->scan_result_.adv_data_len);
      |                                                      ^~~~~~~~~~~~
*** [.pioenvs/fan-contoller/src/esphome/components/ble_adv_controller/ble_adv_handler.cpp.o] Error 1
========================= [FAILED] Took 11.05 seconds =========================`

What i'm doing wrong
Thanks
Mike
