### ISSUE TITLE
Possible compatibility with the RP2040 platform ?

### ISSUE THREAD

**Issue by messiasv** [aronsky/esphome-components#7]
Hi and thank you for your contribution. (I searched to contact you, but couldn't find a way, so I'm asking here)

This repository looks very cool and wanted to try it out.
Currently I own a [Raspberry Pi Pico](https://www.raspberrypi.com/products/raspberry-pi-pico/) W (with WiFi/BLE support) [[RP2040](https://www.raspberrypi.com/products/rp2040/)].
This hardware is supported by ESPHome: https://esphome.io/components/rp2040.html

I'm reaching out to you to ask if it would be possible to port your code to support the RP2040 Platform ?
What would be required ? It would have to be in a different repository ?
Or am I better off getting an esp32 chip ?

Regards.

**Comment by aronsky** [comment]
Contacting here is fine :)

What happens when you use the current code? Does the build fail? If so, what's the error?

**Comment by messiasv** [comment]
Thank you!
I get 2 errors right inside ESPHome editor:
- `Component esp32_ble requires component esp32.`
  ![image](https://github.com/aronsky/esphome-components/assets/15677288/7b21720b-ab7c-4063-b8a6-0100aa82e1d2)

- `Component light.lampsmart_pro_light requires component esp32.`
  ![image](https://github.com/aronsky/esphome-components/assets/15677288/4538ef45-8c53-4659-8d4e-47c904519431)

My configuration:
```yml
esphome:
  name: picow
  friendly_name: picow

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# I omitted: logger, api, ota, wifi, ap

external_components:
  # use lampsmart_pro_light from aronsky/esphome-components's main branch in GitHub
  - source:
      type: git
      url: https://github.com/aronsky/esphome-components
      ref: main
    components: [ lampsmart_pro_light ]

light:
  - platform: lampsmart_pro_light
    name: Kitchen Light
    duration: 1000
    default_transition_length: 0s

```

I did manage to run other code on this raspberry pi pico W (RP2040 Platform).
But I'm guessing it can't run ESP32 code..
For example, this is the code to blink the onboard led:
```yml
Blinking the built-in LED
output:
  - platform: gpio
    pin: 32
    id: led

interval:
  - interval: 1000ms
    then:
      - output.turn_on: led
      - delay: 500ms
      - output.turn_off: led
```
